import React from 'react';
import { Scale, CheckCircle2, ShieldAlert, X } from 'lucide-react';

export default function TermsModal({ isOpen, onClose }) {
  if (!isOpen) return null;

  return (
    <div className="modal show d-block" style={{ backgroundColor: 'var(--modal-backdrop)', zIndex: 1080 }} tabIndex="-1">
      <div className="modal-dialog modal-dialog-centered modal-lg modal-dialog-scrollable">
        <div className="modal-content border shadow-lg" style={{ background: 'var(--modal-bg)', borderColor: 'var(--border-color)', borderRadius: '4px' }}>
          {/* Header */}
          <div className="modal-header px-4 py-3 border-bottom" style={{ background: 'var(--modal-header-bg)', borderColor: 'var(--border-color)' }}>
            <div className="d-flex align-items-center gap-2">
              <div className="p-2 border rounded-1" style={{ background: 'var(--bg-subtle)', borderColor: 'var(--border-color)' }}>
                <Scale size={18} style={{ color: 'var(--brand-primary)' }} />
              </div>
              <div>
                <h5 className="modal-title fw-bold mb-0" style={{ color: 'var(--text-primary)', fontSize: '1.05rem' }}>
                  Enterprise Terms &amp; Conditions of Service
                </h5>
                <span className="small code-font" style={{ color: 'var(--text-secondary)', fontSize: '0.74rem' }}>
                  SaaS Master Services Agreement &bull; Data Processing Standards &bull; SLA
                </span>
              </div>
            </div>
            <button
              type="button"
              onClick={onClose}
              className="btn-close"
              aria-label="Close"
              style={{ filter: 'var(--btn-close-filter)' }}
            />
          </div>

          {/* Body */}
          <div className="modal-body px-4 py-3" style={{ maxHeight: '70vh' }}>
            <div className="p-3 mb-3 border rounded-1" style={{ background: 'var(--bg-subtle)', borderColor: 'var(--border-color)' }}>
              <div className="fw-bold small mb-1" style={{ color: 'var(--text-primary)' }}>
                Commercial Scope &amp; Binding Agreement
              </div>
              <p className="small mb-0" style={{ color: 'var(--text-secondary)', lineHeight: 1.6, fontSize: '0.82rem' }}>
                By accessing or submitting documents to the HireScope ATS platform, client enterprises, recruiters, and candidates agree to be bound by these Terms of Service governing document processing, automated semantic evaluations, and system availability.
              </p>
            </div>

            <div className="mb-3">
              <h6 className="fw-bold mb-1 small text-uppercase tracking-wider" style={{ color: 'var(--text-primary)', fontSize: '0.76rem' }}>
                1. Acceptable Document Uploads
              </h6>
              <p className="small mb-0" style={{ color: 'var(--text-nav)', lineHeight: 1.6, fontSize: '0.82rem' }}>
                Clients and users agree to submit authentic, uncorrupted PDF documents representing genuine curriculum vitae and career backgrounds. Submitting malicious binary payloads, embedded scripts, or unauthorized third-party personal identifiers is strictly prohibited and subject to immediate termination.
              </p>
            </div>

            <div className="mb-3">
              <h6 className="fw-bold mb-1 small text-uppercase tracking-wider" style={{ color: 'var(--text-primary)', fontSize: '0.76rem' }}>
                2. Nature of Automated Semantic Evaluations
              </h6>
              <p className="small mb-0" style={{ color: 'var(--text-nav)', lineHeight: 1.6, fontSize: '0.82rem' }}>
                Match scores (0-100%) and feedback summaries generated by the platform represent computational analysis of textual overlap and semantic proficiency against the provided job requisition. The evaluation serves as an algorithmic decision-support tool and does not constitute a legal endorsement or binding employment decision.
              </p>
            </div>

            <div className="mb-3">
              <h6 className="fw-bold mb-1 small text-uppercase tracking-wider" style={{ color: 'var(--text-primary)', fontSize: '0.76rem' }}>
                3. System Availability &amp; Service Level Commitments
              </h6>
              <p className="small mb-0" style={{ color: 'var(--text-nav)', lineHeight: 1.6, fontSize: '0.82rem' }}>
                HireScope ATS targets a 99.9% uptime SLA for asynchronous ingestion endpoints (HTTP 202 Accepted) and Server-Sent Events streams. In standalone demo deployments, client-side dynamic evaluation failover ensures zero operational disruption.
              </p>
            </div>

            <div className="mb-2">
              <h6 className="fw-bold mb-1 small text-uppercase tracking-wider" style={{ color: 'var(--text-primary)', fontSize: '0.76rem' }}>
                4. Intellectual Property &amp; Resume Ownership
              </h6>
              <p className="small mb-0" style={{ color: 'var(--text-nav)', lineHeight: 1.6, fontSize: '0.82rem' }}>
                Candidates retain full copyright ownership of submitted resumes and documents. The platform receives only a limited, non-exclusive license strictly necessary to parse, index, and score the document for the hiring entity.
              </p>
            </div>
          </div>

          {/* Footer */}
          <div className="modal-footer px-4 py-2 border-top" style={{ background: 'var(--modal-header-bg)', borderColor: 'var(--border-color)' }}>
            <button type="button" onClick={onClose} className="btn btn-sm btn-brand-solid px-3">
              Accept Terms &amp; Close
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
